### ISSUE TITLE
Exporting the same MDL0 material twice causes NRE

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#130]
Export the same material twice from any model and observe the following NRE:

Object reference not set to an instance of an object.
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialRefNode.PostProcess(VoidPtr mdlAddress, VoidPtr dataAddress, StringTable stringTable)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialNode.PostProcess(VoidPtr mdlAddress, VoidPtr dataAddress, StringTable stringTable)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialNode.Export(String outPath)
   at BrawlBox.NodeWrappers.GenericWrapper.OnExport(String outPath, Int32 filterIndex) in C:\Users\Meredith\Source\Repos\brawltools\BrawlBox\NodeWrappers\GenericWrapper.cs:line 122
   at BrawlBox.NodeWrappers.GenericWrapper.Export() in C:\Users\Meredith\Source\Repos\brawltools\BrawlBox\NodeWrappers\GenericWrapper.cs:line 118
   at BrawlBox.NodeWrappers.GenericWrapper.ExportAction(Object sender, EventArgs e) in C:\Users\Meredith\Source\Repos\brawltools\BrawlBox\NodeWrappers\GenericWrapper.cs:line 31
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by libertyernie** [comment]
Here's what I could figure out so far:
* When you export (and the material is not modified), it copies the data from WorkingSource.Address (ResourceNode.cs line 703)
* The first time through, _replSrc is empty and so WorkingSource points to _origSource. But then it sets _replSrc - I think it points it at the just exported file. This seems to be true for any kind of ResourceNode.
* The second time, it copies from _replSrc. This time, _matRefOffset in the MDL0Material struct is 0.
