### ISSUE TITLE
Null Reference Exception when importing attached WAV through BRSTM Audio Stream

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#140]
[Lloyd.zip](https://github.com/libertyernie/brawltools/files/1165580/Lloyd.zip)
The following error occurs when importing the attached WAV file into Brawlbox. Brawlbox v0.68b does not have this problem:

Object reference not set to an instance of an object.
   at System.Windows.Forms.BrstmConverterDialog..ctor()
   at BrawlBox.MainForm.bRStmAudioToolStripMenuItem_Click(Object sender, EventArgs e) in C:\Users\Ryan!\Source\Repos\brawltools\BrawlBox\UI\MainForm.cs:line 532
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by libertyernie** [comment]
Looks like an oversight on my part. Should be fixed now.
