### ISSUE TITLE
BrawlBox crashes when exporting sound in a BRSAR to a WAV file.

### ISSUE THREAD

**Issue by danfiscus** [libertyernie/brawltools#155]
Using the /Sound/WZSound.brsar file in a Legend of Zelda Skyward Sword ISO, I cannot export any contained sound files to an Uncompressed WAV. I tried again with sounds in other brsar files and had the same issue regardless of the game. Here is the error message I got:
```
Object reference not set to an instance of an object.
   at System.Audio.WAV.ToByteArray(IAudioStream source, Int32 samplePosition, Int32 maxSampleCount, Boolean appendSmplChunk)
   at BrawlLib.SSBB.ResourceNodes.RSARSoundNode.Export(String outPath)
   at BrawlBox.NodeWrappers.GenericWrapper.OnExport(String outPath, Int32 filterIndex)
   at BrawlBox.NodeWrappers.GenericWrapper.Export()
   at BrawlBox.NodeWrappers.GenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by libertyernie** [comment]
Could you post a link to one of those brsar files?

**Comment by danfiscus** [comment]
@libertyernie The brsar sound file from Skyward Sword can be found here: 
http://danfisc.us/uploads/WZSound.7z

**Comment by libertyernie** [comment]
Apparently only RWSD nodes can be converted to WAV (or played), and not RSEQ nodes or other types. I don't know much about .brsar so I don't think I can fix it.

**Comment by MasterKingSirPlease** [comment]
Been having issues with Skyward Sword audio myself

**Comment by zimonitrome** [comment]
Does anyone know an alternative way to export these sounds?
