### ISSUE TITLE
Importing the Object in the Model

### ISSUE THREAD

**Issue by DeriLoko3** [libertyernie/brawltools#179]
I was replacing the object with another object in the model, but Brawlbox had the unexpected error.

`Object reference not set to an instance of an object.
   at BrawlLib.SSBB.ResourceNodes.MDL0ObjectNode.OnInitialize()
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.ReplaceRaw(FileMap map)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Replace(String fileName, FileMapProtect prot, FileOptions options)
   at BrawlLib.SSBB.ResourceNodes.ResourceNode.Replace(String fileName)
   at BrawlBox.NodeWrappers.GenericWrapper.OnReplace(String inStream, Int32 filterIndex)
   at BrawlBox.NodeWrappers.GenericWrapper.Replace()
   at BrawlBox.NodeWrappers.GenericWrapper.ReplaceAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam`

I use BrawlBox (v0.78) (Hotfix 1) in Windows 10 Home Insider Preview (x64).

**Comment by Ebola16** [comment]
I probably came across the same issue so I'll post my steps to reproduce the problem here using these files: [Palutena Brawlbox Error.zip](https://github.com/libertyernie/brawltools/files/3934809/Palutena.Brawlbox.Error.zip)

1. In Brawlbox v0.78, open FitPalutena01.pac and look at FitPalutena00.mdl0
2. Import Existing object Gates.mdl0 with the following settings:
![Capture](https://user-images.githubusercontent.com/17330088/70370122-67dbbd00-1891-11ea-806b-6730e050111f.PNG)
3. Observe:
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Windows.Forms.ObjectImporter.btnOkay_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

This issue does not occur in Brawlbox v0.68b
