### ISSUE TITLE
Export all problem

### ISSUE THREAD

**Issue by ad48hp** [libertyernie/brawltools#196]
Exporting a folder "Attraction/At015" that contained about 15 brres files.
https://1drv.ms/u/s!ApTusXylYbest1g-JxZo7453GJa0
Noice bug report system m9 tho. I used it to report the bug, but i would rather write it myself here too. ( ͡° ͜ʖ ͡°)

```
Unable to cast object of type 'BrawlLib.SSBB.ResourceNodes.U8FolderNode' to type 'BrawlLib.SSBB.ResourceNodes.BRRESNode'.
   at BrawlBox.NodeWrappers.U8FolderWrapper.ExportAll()
   //Unimportant bulšit from now on xdýdýdý
   at BrawlBox.NodeWrappers.U8FolderWrapper.ExportAllAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

_Also_, when i export an entire brres file, it asks me which format i want to save the textures in, but don't ask to save the models as dae..

**Comment by libertyernie** [comment]
I don't really know how to fix this.

@Sammi-Husky @BlackJax96 @soopercool101  any ideas?

**Comment by soopercool101** [comment]
The presence of <null> named objects would be my guess. I'll look into it

**Comment by soopercool101** [comment]
Okay figured out it appears to be due to an invalid cast. It casts all these as ARCs and BRRES's and runs their equivalent functions, which doesn't work proper. Writing actual ExportAll functions for U8 and U8 Folders will fix this
