### ISSUE TITLE
Index outside the bounds of array when importing attached texture

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#211]
Import this texture into a MiscData BRES file
![hello w](https://user-images.githubusercontent.com/17330088/52179734-e2d4d280-27ab-11e9-8b04-8e5efde9bed2.PNG)

and receive:
Index was outside the bounds of the array.
   at System.BitmapExtension.GuessIfAlphaInverted(Bitmap bmp)
   at System.Windows.Forms.TextureConverterDialog.Recommend()
   at System.Windows.Forms.TextureConverterDialog.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)

**Comment by libertyernie** [comment]
This is in code I wrote, so I ought to be able to fix it :)
