### ISSUE TITLE
Impossible to extract BRSAR file from Art Style games series

### ISSUE THREAD

**Issue by iyenal** [libertyernie/brawltools#62]
When I try to export a WAV file from a BRSAR sound archive of Art Style series, BrawlBox throw an error and I'm also unable to play it into the editor.

Pleas fix the problem. Thanks.

**Comment by awesomebing1** [comment]
I believe I'm getting a similar issue with the Tennis sound from Wii Sports, are you getting something similar to the below?

```
Object reference not set to an instance of an object.
   at System.Audio.WAV.ToFile(IAudioStream source, String path, Int32 samplePosition, Int32 maxSampleCount)
   at BrawlLib.SSBB.ResourceNodes.RSARSoundNode.Export(String outPath)
   at BrawlBox.GenericWrapper.OnExport(String outPath, Int32 filterIndex)
   at BrawlBox.GenericWrapper.Export()
   at BrawlBox.GenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by libertyernie** [comment]
The Art Style RSAR appears to be a different format than the ones BrawlBox knows how to read. I'm not very familiar with RSAR so I personally can't fix it (at least not right now.)

The Wii Sports issue looks like a separate issue.
@awesomebing1 - could you post a link to the brsar you're using?

**Comment by awesomebing1** [comment]
@libertyernie Please see #81.

**Comment by GamingKitty** [comment]
I've been trying to change the sound files from Wii Sports and haven't been able to get any audio except for the music. I suppose this is the problem. I hope this can be solved in the future!
