### ISSUE TITLE
Wii Sports (Tennis) results in error upon exporting of WAV

### ISSUE THREAD

**Issue by awesomebing1** [libertyernie/brawltools#81]
(I mentioned this in #62 but it appears it is a different issue, so I created a new one.)

Upon opening the Tennis .brsar (which can be downloaded [here](https://keybase.pub/awesomebing1/rp_Tns_sound.brsar), the format loads as expected however some cannot be played. For example, anything in FANFARE/ or Fanfare/ or Bgm/ can be played, same in Bgm/, but things in BGM/ and STRM/ and several other places cannot be played. Attempting to export non-playable sounds result in the following error:

```
Object reference not set to an instance of an object.
   at System.Audio.WAV.ToFile(IAudioStream source, String path, Int32 samplePosition, Int32 maxSampleCount)
   at BrawlLib.SSBB.ResourceNodes.RSARSoundNode.Export(String outPath)
   at BrawlBox.GenericWrapper.OnExport(String outPath, Int32 filterIndex)
   at BrawlBox.GenericWrapper.Export()
   at BrawlBox.GenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by libertyernie** [comment]
I noticed that when you select one of these non-exportable sounds, there's a SoundFile field with the name of a .brstm.
Does this .brstm exist on the Wii Sports disc? Maybe the sound you're looking for isn't in the .brsar file at all.

![untitled](https://cloud.githubusercontent.com/assets/3732811/19523207/6fdcd4ea-95df-11e6-89b5-09f259ae818d.png)

**Comment by awesomebing1** [comment]
I can confirm that file is there, in the stream folder.

```
> ls -R
.:
rp_Tns_sound.brsar  stream

./stream:
RP_Tns_Bgm_GameResultDisp.t.32.c4.brstm  RP_Tns_Bgm_TrainingResultDisp.t.32.c4.brstm  RP_Training_Bgm_Result03.t.32.c4.brstm       RP_Training_Tns_Bgm_Renzoku.t.32.c4.brstm
RP_Tns_Bgm_GameSetReplay.t.32.c4.brstm   RP_Training_Bgm_Result01.t.32.c4.brstm       RP_Training_Tns_Bgm_Kabeuchi.t.32.c4.brstm
RP_Tns_Bgm_SelectPosition.t.32.c4.brstm  RP_Training_Bgm_Result02.t.32.c4.brstm       RP_Training_Tns_Bgm_Nerauchii.t.32.c4.brstm
```

I personally had not noticed that folder existed, my fault for not seeing it. Upon opening the file (which can be dowloaded [here](https://keybase.pub/awesomebing1/RP_Training_Tns_Bgm_Nerauchii.t.32.c4.brstm)) in BrawlBox, all I heard was a bunch of static.

I was able to reproduce both of these issues on a Windows 8.1 64bit and Windows XP 32bit installation, both running in Parallels on my Mac. (These files were not stored via Parallel's virtual file handling thing, I copied them to the local drive.)

**Comment by libertyernie** [comment]
The file is encoded differently than the ones in Brawl (it's just PCM16, except encoded in blocks and not interlaces like WAV files are).
I added support for decoding them, so that will be in the next version. Until then, you could use vgmstream to convert them to WAV.
