### ISSUE TITLE
"Regenerate Metal Materials" can corrupt materials

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#95]
"Regenerate Metal Materials" can corrupt materials (tested on Dolphin and real Wii).
Here are the models shown below [Metal Corrupt.zip](https://github.com/libertyernie/brawltools/files/644260/Metal.Corrupt.zip)

Original (before adding metal materials):
![capturjjjje](https://cloud.githubusercontent.com/assets/17330088/21078505/2a9230e4-bf40-11e6-88f4-b89c41000d55.PNG)

After adding metal materials:
![corrupt](https://cloud.githubusercontent.com/assets/17330088/21078498/a3caebc8-bf3f-11e6-87b5-92fe3ecdb984.PNG)

**Comment by Ebola16** [comment]
Some insight on what's going on. The original and corrupted textures are different sizes when exported from Brawlbox. Possible byte-counters also seem to be adjusted for the corrupted material's new size.
![cme](https://cloud.githubusercontent.com/assets/17330088/21929775/a2a4e81c-d960-11e6-84c0-0812cd7eb9ec.PNG)

I have attached the materials exported from my tests. 
[Materials.zip](https://github.com/libertyernie/brawltools/files/704233/Materials.zip)

The original material05 before any metal generation works properly in game. Generating metal materials then exporting material05 BEFORE saving produced one result (not truncated). Generating metal materials, saving, then exporting material05 produced another (truncated).

Additionally, exporting material05 repeatedly will either successfully export a file, crash Brawlbox, or produce this NRE:

>   Object reference not set to an instance of an object.
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialRefNode.PostProcess(VoidPtr mdlAddress, VoidPtr dataAddress, StringTable stringTable)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialNode.PostProcess(VoidPtr mdlAddress, VoidPtr dataAddress, StringTable stringTable)
   at BrawlLib.SSBB.ResourceNodes.MDL0MaterialNode.Export(String outPath)
   at BrawlBox.GenericWrapper.OnExport(String outPath, Int32 filterIndex)
   at BrawlBox.GenericWrapper.Export()
   at BrawlBox.GenericWrapper.ExportAction(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripMenuItem.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ToolStripManager.ProcessShortcut(Message& m, Keys shortcut)
   at System.Windows.Forms.ToolStripManager.ProcessCmdKey(Message& m, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Form.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

**Comment by Ebola16** [comment]
[Metal Materials.zip](https://github.com/libertyernie/brawltools/files/704255/Metal.Materials.zip)
The metal materials also are different before and after saving when they are first generated.

**Comment by Ebola16** [comment]
Four bytes (00 00 00 00) are missing at 0x460 in material05's corrupted form. Any idea what's going on there?

**Comment by Ebola16** [comment]
Another example:
Generate metal materials for http://forums.kc-mm.com/Gallery/BrawlView.php?Number=36138 and this will occur in game.
![capturerew](https://user-images.githubusercontent.com/17330088/31853808-1eb4e6da-b65d-11e7-827e-e45809e3508a.PNG)

I re-rigged the model in 3ds Max 2016 and metal materials could be properly generated by Brawlbox. See http://forums.kc-mm.com/Gallery/BrawlView.php?Number=214918.

Comparing these may be useful.

**Comment by Ebola16** [comment]
I think I figured out how to reproduce this issue:
1. Import any DAE with "ForceFloatNormals" or "ForceFloatUVs" set to False
2. Generate Metal Materials
3. Observe the messed up textures in Dolphin or a real Wii. Brawlbox will properly display the textures.

Maybe something in the material creation process doesn't account for "ForceFloatNormals" or "ForceFloatUVs" being set to False?

**Comment by BlackJax96** [comment]
Metal materials need texture matrices for non-single-bound objects, which don't work at all with non-float UVs. Same explanation as my answer on the other issue you posted.

I'll go ahead and close these two topics in a few days since they're not something that can be fixed.

**Comment by Ebola16** [comment]
Reopening since BlackJax96's idea is a proper fix:

> An optimal scenario would be to show a popup if the user (or code, in the case of metal materials) turns on a texture matrix for an object but one of the attached uv sets doesn't use float values. The popup could ask if you want to force float UVs or not.
